@echo off
CD %~dp0
echo Download prerequisites to create installer
call get-tools.bat > get-tools.log
echo Download cygwin...
call cyg-download.bat >  cyg-download.log
echo Install cygwin in temporal directory...
call cyg-install.bat > cyg-install.log
echo Download PHP...
call get-php.bat > get-php.log
echo Download eclipse/JRE/plugins...
call eclipse-dl.bat > eclipse-dl.log
echo Download arm gcc embedded...
call arm-embedded-dl.bat > arm-embedded-dl.log
echo Download OpenOCD...
call openocd-dl.bat > openocd-dl.log
echo Download NSIS...
call nsis-dl.bat > nsis-dl.log
echo Done.
pause
