@echo off
CD %~dp0
echo Download prerequisites to create installer
call get-tools.bat
echo Download cygwin...
call cyg-download.bat
echo Install cygwin in temporal directory...
call cyg-install.bat
echo Download eclipse/JRE/plugins...
call eclipse-dl.bat
echo Download arm gcc embedded...
call arm-embedded-dl.bat
echo Download NSIS...
call nsis-dl.bat
echo Done.
pause
